import React from 'react'
import {render, fireEvent} from '@testing-library/react'
import  HeadingTwo from '../components/typography/HeadingTwo'
import '@testing-library/react/cleanup-after-each'
import '@testing-library/jest-dom/extend-expect'